name: Tested on Linux, MacOS, Windows

on: [push, pull_request]

jobs:
  tests:
    runs-on: ${{ matrix.platform }}
    name: "Python ${{ matrix.python-version }}"
    env:
      USING_COVERAGE: '3.8'

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        # platform: [ubuntu-latest, macos-10.15]
        # Tox py39 environments run locally.. but
        # actually maybe 3.9 has some problem with pytables?
        # https://github.com/freqtrade/freqtrade/issues/4162

        # python-version: ["3.7", "3.8", "3.9"]
        python-version: ["3.7", "3.8"]

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v1"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools
          python -m pip install --upgrade coverage[toml] virtualenv tox tox-gh-actions
      - name: "Run tox targets for ${{ matrix.platform }} ${{ matrix.python-version }}"
        run: "python -m tox -- -m 'not ghskip'"
      - name: "Get coverage"
        run: |
          python -m coverage combine
          python -m coverage xml
        if: "contains(env.USING_COVERAGE, matrix.python-version)"
      - name: Upload coverage to Codecov
        if: "contains(env.USING_COVERAGE, matrix.python-version)"
        uses: "codecov/codecov-action@v1"
        with:
          fail_ci_if_error: true